export const RequestType = {
  EDIT_COURSE: "EDIT_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  ADD_MODULE: "ADD_MODULE",
  EDIT_MODULE: "EDIT_MODULE",
  DELETE_MODULE: "DELETE_MODULE",
  EDIT_FINAL_QUIZ: "EDIT_FINAL_QUIZ",

  RESET_QUIZ_ATTEMPTS: "RESET_QUIZ_ATTEMPTS",
  EXTENSION_REQUEST: "EXTENSION_REQUEST",
  REFUND_REQUEST: "REFUND_REQUEST",
  CERTIFICATE_ISSUE: "CERTIFICATE_ISSUE",
};
